Implement showing transfered file in folder as default action of notification (single click)
GSConnect/gnome-shell-extension-gsconnect pull request #1039
Opened 2021-01-03 21:15 UTC by HaMF

This adresses issue #1009, but probably needs some work. See issue discussion for details

2021-06-19 09:12 UTC, sonnyp requested changes
Thanks! - and sorry for the late review

> if we want to use this behavior when "Open Folder is clicked

Yes. This is better.

For the label, I think GNOME already has a wording for this action but I couldn't find it. Otherwise I'd suggest "Show in folder". 

Given this is a GNOME Shell extension, I don't think we need the previous method as fallback.

> if dbus is really the only way to achieve this (that's what I found, should work for nautilus and dolphin)

Yep, there are no wrapper exposed in GNOME libraries AFAIK

https://github.com/search?q=org.freedesktop.FileManager1&type=code

> how tests can be added

I wouldn't say it's necessary here. But if you like checkout `installed-tests/suites/components/`. I guess you could listen on the bus and wait for what's of interested.

@andyholmes wdyt? any better idea for testing this?

> how I can check the transfer-failed notification works

Perhaps send a large file and disconnect network midway. Why is it relevant?

2021-06-19 09:12 UTC, sonnyp commented on src/service/device.js
> +        );
looks like there should be an error to catch here

https://www.andyholmes.ca/articles/dbus-in-gjs.html#direct-calls

Logging the error is enough.

2021-06-19 09:14 UTC, sonnyp commented on src/service/device.js
> +    openPathSelectFile(action, parameter) {
consider renaming to `showPathInFolder`

2021-06-19 20:12 UTC, andyholmes commented
> I wouldn't say it's necessary here. But if you like checkout `installed-tests/suites/components/`. I guess you could listen on the bus and wait for what's of interested.
> 
> @andyholmes wdyt? any better idea for testing this?

I don't think there are many UI tests in the suite yet, those are kind of hard to do in a CI at the moment. Probably this one would just have to be tested locally.

2022-05-22 23:28 UTC, ferdnyc commented
Jumping in way late on this, but I may pick it up if @HaMF doesn't plan to continue.

@HaMF 
> > if we want to use this behavior when "Open Folder is clicked
@sonnyp 
> Yes. This is better.
> 
> For the label, I think GNOME already has a wording for this action but I couldn't find it. Otherwise I'd suggest "Show in folder".

The Nautilus wording (seen in both the Recent list and Search results is "Open Item Location". Which I suppose may not technically be a folder, so I have to give them that. (It may be at the root of a removable drive, for example.)

However, when _outside_ the file manager itself, the wording is usually different. Common are:

* "Show in folder" (Chrome & Firefox download lists)
* "Open Containing Folder" (Evince, GNOME Builder)
* No text since there's just a 📁 icon with no tooltip, JFC. (GNOME Web)
* No idea, it has never found a single photo on my system (which contains plenty of photos). (GNOME Photos)

2022-05-23 19:27 UTC, HaMF commented
@ferdnyc Thanks for the research regarding the wording. Feel free to take it and finish it, I won't get around to it in the next days. If you haven't done so until next week when I'm back I'll look into it.

@sonnyp thanks for the review and the valuable pointers. Sorry must have missed the notification. I'll check in detail if ferdnyc does not pick it up

2022-10-17 15:00 UTC, ferdnyc commented on src/service/device.js
> +        const uri = path.includes('://') ? path : `file://${path}`;
@sonnyp Looking at this again, I wonder if that's really necessary. By the time it gets here, the uri has _already_ been through `Gio.File`:
https://github.com/GSConnect/gnome-shell-extension-gsconnect/blob/4208acc233bb2757b8c84c19e74715413961b06c/src/service/plugins/share.js#L179-L189

The URI coercion here is (as I read it) just a safety valve, _in case_ someone adds a call to `openPath()` (or `openPathSelectFile()`) with a bare pathname. But in normal/expected usage, the parameter is the result of a `file.get_uri()` already. Round-tripping through `Gio.File` a second time may be overkill?

2022-10-19 09:08 UTC, ferdnyc commented
I've submitted #1491 containing both @HaMF's commits from this PR (thanks, @HaMF!), as well as my further changes to address the review input here.

This can probably be closed in favor of #1491. I'll wait a bit, tho, so others have time to look over that PR and decide whether it's the right path.

2022-10-20 12:52 UTC, closed without merging