Cli support for general wayland environment
GSConnect/gnome-shell-extension-gsconnect pull request #1322
Opened 2022-04-02 14:32 UTC by JingMatrix

This commit use `wl-clipboard` and `ydotool` to support general wayland environment, such as sway.

2022-04-08 07:30 UTC, JingMatrix commented
Please tell me if you have intention to extend this plugin to non-gnome environment, @ferdnyc @andyholmes .
If so, I can add a page to the project wiki to show how it actually works.

2022-04-08 20:41 UTC, andyholmes commented
I don't have much of an opinion on this. GSConnect was intended to be specifically for GNOME Shell, but if another maintainer wants to give it a :+1: I won't stand in the way :slightly_smiling_face:

2022-05-22 09:13 UTC, daniellandau commented
I have limited time for maintenance, so if making it more generic comes with associated maintenance effort on an ongoing basis I'm all for it. I'll read through the code hopefully soon.

2023-06-15 18:09 UTC, andyholmes requested changes
Sorry this sat around for so long. I don't see any reason not to merge at this point, so a few fixups and I will accept this.

2023-06-15 18:09 UTC, andyholmes commented on src/service/components/clipboard.js
> +                this.signalHanlder = Gio.DBus.session.signal_subscribe(
```suggestion
                this.signalHandler = Gio.DBus.session.signal_subscribe(
```

2023-06-15 18:09 UTC, andyholmes commented on src/service/components/clipboard.js
> +            Gio.DBus.session.signal_unsubscribe(this.signalHanlder);
```suggestion
        if (!HAVE_GNOME && this.signalHandler)
            Gio.DBus.session.signal_unsubscribe(this.signalHandler);
```

2023-06-15 18:18 UTC, andyholmes commented
Oh, just one more thing: add the SPDX comments to `ydotool.js` and `wl_clipboard.js` like so:

```js
// SPDX-FileCopyrightText: GSConnect Developers https://github.com/GSConnect
//
// SPDX-License-Identifier: GPL-2.0-or-later
```

2023-06-15 21:36 UTC, JingMatrix commented
Thanks for reviewing.
Unfornately, I have forgotten most of the logic of gsconnect, though I am using this pull request for the whole year.
It seems after merging the main branch, remote mousepad isn't working. I need some time to debug it.
Also, I should add a wiki page to explain the usage.

2023-06-15 23:04 UTC, andyholmes commented
Okay, no problem. I don't expect many folks will start using this for a little while, at least.

If you can get it working for you, we can merge and you can be "codeowner" for that module, if you like.

2023-06-15 23:30 UTC, JingMatrix commented
I test it on my machine with both sway and gnome-shell sessions,  and there is no problem. (It turned out that I forgot to start ydotoold in sway.)
I would be happy to maintain this module.

### Notes for dev
1. The enviroment variable `XDG_SESSION_TYPE`  is not reliable as user can change it or it is not set at all, but gnome doesn't change it back to 'gnome'.
2. Not sure how to pass the test that gives error:
```
(gjs:475): Gjs-WARNING **: 18:11:09.216: JS ERROR: Mock Backend: ImportError: No JS module 'ydotool' found in search path
mockComponents/Components.acquire@/usr/libexec/installed-tests/gsconnect/fixtures/utils.js:230:9
```

### Notes for users
When `gsconnect` is not running as a Gnome extension, for example, running under `sway`,
1. You might still  need to install the `gnome-shell` package to provide the `Gvc-1.0.typelib` file of the gnome module `libgnome-volume-control`.
4. Install `ydotool` and start the service: systemctl status --user ydotool.service 
5. Install `wl-clipboard` and `wl-type`

2023-06-16 00:57 UTC, JingMatrix commented
I found that the env GNOME_SETUP_DISPLAY is specially set by gnome, which can thus be used to detect gnome.

Now this pull request should pass all tests without problems, you can merge it.

P.S. it might be interesting to write a test for non-gnome envirment, maybe in the future.

2023-06-16 04:19 UTC, andyholmes commented
> P.S. it might be interesting to write a test for non-gnome envirment, maybe in the future.

Definitely, I saw somewhere I think Google Chrome or Chromium had a Wayland version of xvfb built with python or something. I never had time to really get into it though.

2023-06-16 05:53 UTC, merged

2023-06-16 09:36 UTC, JingMatrix commented
As a note, I add the wiki page of its usage: [CLI usage without Gnome](/GSConnect/gnome-shell-extension-gsconnect/wiki/CLI-usage-without-Gnome-environment).

It will be helpful to put some instructions described there into the meson build process.

2023-06-17 21:17 UTC, andyholmes commented
That's great, thanks for writing all that up!

2023-12-05 10:16 UTC, JingMatrix commented
Given what said by @pobrn , it is better not to use environment variable for detecting the 'Gnome'.
I was for using `imports` to detect `Gnome`, @andyholmes changed it out of the reason of simplicity (I guess).
Hence, it is favorable to revert the changes regarding the environment variable.
I will do it soon to fix #1706.

2023-12-05 15:48 UTC, andyholmes commented
FWIW, [this was my suggestion](https://github.com/GSConnect/gnome-shell-extension-gsconnect/pull/1322#discussion_r1231377133):

> This won't work in the service, because it's runs outside of the `gnome-shell` process (meaning it will always throw an error). However, I think this would work:
> 
> ```js
> const HAVE_GNOME = GLib.getenv('XDG_SESSION_TYPE') === 'gnome'
> ```
> 
> You can put this in `src/service/__init__.js` as `globalThis.HAVE_GNOME` if you want, or leave it here.

2023-12-05 16:50 UTC, JingMatrix commented
@andyholmes Thanks for mentioning it, I totally forgot it. So I guess we may use the existence of the directory `/usr/share/cinnamon/js/ui/*` as a detector.

Or, alternatively, is there a way to communicate bewteen the `extention.js` and `daemon.js`?
If so, we can set `HAVE_GNOME` in `extension.js`.

2023-12-05 17:39 UTC, JingMatrix commented
I propose to use `imports.gi.Shell` as a heuristic for setting `HAVE_GNOME`.
See my pull-request for details: https://github.com/GSConnect/gnome-shell-extension-gsconnect/pull/1715#issuecomment-1841296211