GSconnect vulnerable to man-in-the-middle attack due to compatibility [Potential Fix]
GSConnect/gnome-shell-extension-gsconnect pull request #1638
Opened 2023-06-11 08:07 UTC by mrdev023

I enable all version of TLS like in https://invent.kde.org/network/kdeconnect-android/-/commit/e2dbc39e3a73cc6c7cf1c27362e4f2b768e88f42

It's my first contribution.

This PR can fix #1606

2023-06-18 01:58 UTC, andyholmes requested changes
Thanks for the contribution!

If you want to remove the exception for TLS 1.0, you should just removed this entire block and let `glib-networking` handle keeping up with current security notices.

However, it is worth pointing out again that this will very much not help with MITM attacks. #987 contains a number of far more critical vulnerabilities.

2023-06-18 01:58 UTC, andyholmes commented on src/service/daemon.js
>  // See https://github.com/GSConnect/gnome-shell-extension-gsconnect/issues/930
```suggestion
```

2023-06-18 01:58 UTC, andyholmes commented on src/service/daemon.js
> +imports.gi.GLib.setenv('G_TLS_GNUTLS_PRIORITY', 'NORMAL:%COMPAT:+VERS-ALL', true);
```suggestion
```

2023-08-25 22:48 UTC, closed without merging

2023-11-13 17:32 UTC, bernieEV commented
I have Ubuntu 22.04LTS with GSconnect and Android14 with KDEconnect
All is working fine. I did a wireshark trace on ethernet and found **TLSv1.2**
I want to limit TLS to version 1.3 only. how to ?

2023-11-13 17:42 UTC, andyholmes commented
If you want to restrict to TLSv1.3 you can muck around with this line:

https://github.com/GSConnect/gnome-shell-extension-gsconnect/blob/gnome-43/src/service/daemon.js#L11

This has been removed in the latest version, so you'll have to carry a patch yourself. The upstream documentation for this is here: [GnuTLS Priority Strings](https://gnutls.org/manual/html_node/Priority-Strings.html).